version: '2.2'

services:
  apt-cacher-ng:
    restart: always
    image: innovanon/docker-apt-cacher-ng:latest
    init: true
    ports:
    - "3142:3142"
    volumes:
    - acngvol:/var/cache/apt-cacher-ng
volumes:
  acngvol:

