version: '3.3'

services:
  apt-cacher-ng:
    restart: always
    image: innovanon/docker-apt-cacher-ng:latest
    container_name: innovanon/docker-apt-cacher-ng
    #init: true
    ports:
    - "3142:3142"
    volumes:
    - acngvol:/var/cache/apt-cacher-ng
volumes:
  acngvol:

